# Generated by Django 4.2.7 on 2023-12-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="message_files/"),
        ),
    ]
