# Generated by Django 4.2.7 on 2023-12-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_rename_file_message_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
