# Generated by Django 4.2.7 on 2023-12-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_message_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
