# Generated by Django 4.2.7 on 2023-12-06 23:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_task_deadline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="deadline",
        ),
    ]
