# Generated by Django 4.2.7 on 2023-12-06 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_remove_task_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 7, 23, 18, 29, 263338, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
