# Generated by Django 4.2.7 on 2023-12-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
